language: ruby
sudo: required

env:
  global:
    - ORACLE_COOKIE=sqldev
    - ORACLE_FILE=oracle11g/xe/oracle-xe-11.2.0-1.0.x86_64.rpm.zip
    - ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe
    - ORACLE_SID=XE

cache:
  - directories:
    - .cache

before_install:
  - mkdir -p .cache && cp -rt .cache .travis/oracle
  - test -f ".cache/oracle/$( basename $ORACLE_FILE )" || .cache/oracle/download.sh
  - .cache/oracle/install.sh

script: make
